language: python
matrix:
  include:
    - python: "2.7"
    - python: "2.7.13"
    - python: "3.6"
    - python: "nightly"
  allow_failures:
    - python: "2.7"
    - python: "3.6"
    - python: "nightly"

# command to install dependencies
install:
  - pip install python-dateutil pytest mock python-coveralls pytest-cov coverage
# command to run tests
script:
  - py.test --cov coveralls --cov-report term-missing --cov=resources tests/

after_success:
  - coveralls
